### PR TITLE
MySQL 8.0+ compatibility on FreeBSD

### PR DESCRIPTION
**Pull request by metacreo**
MySQL 8.0+ compatibility on FreeBSD.
Fix build with MySql 8.0+ on FreeBSD system.

### Proof

- Unavailable to build any cmangos src on UNIX LIKE with MySql 8.0
```
In file included from /opt/wow/mangos/src/shared/Database/DatabaseEnv.h:41:
/opt/wow/mangos/src/shared/Database/DatabaseMysql.h:59:75: error: unknown type name 'my_bool'
        static enum_field_types ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned);
```
### Issues

- fix build cmangos on FreeBSD with MySql 8.0+

### How2Test

- try to build on freebsd12+mysql80-server

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by cyberium** [comment]
Thank you very much should be fixed now.
